platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: git-repo
  - name: version
  
outputs:
- name: artifacts
  
run:
  path: ./git-repo/concourse/deploy/tasks/build-package.sh  
params: {version: version/number}
